services:
- type: web
  name: rabbitmq
  env: docker
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    generateValue: true
  - key: RABBITMQ_DEFAULT_USER
    value: six
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: 420blazeit
